name: Build

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.REGISTRY_PASSWORD}}    
        
      - name: Restore
        run: dotnet restore  
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish 
        run: dotnet pack Hexio.DineroClient -c Release --no-build -o D:\tmp\output\ -p:PackageVersion=1.0.${env:BUILD_NUMBER}
        
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/mortenrickirasmussen/index.json -Username mortenrickirasmussen -Password ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to registry
        run: nuget push D:\tmp\output\*.nupkg -Source "GPR"