name: Build

on:
  release:
    types: 
      - created
      - updated
  
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: test
        run: ${GITHUB_REF:10}

      - name: Checkout repository
        uses: actions/checkout@master   
        
      - name: Restore
        run: dotnet restore  
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish 
        run: dotnet pack Hexio.DineroClient -c Release --no-build -o /tmp/nuget -p:PackageVersion=${GITHUB_REF:10}
        
      - name: Push to registry
        run: dotnet nuget push /tmp/nuget/*.nupkg -k ${{ secrets.REGISTRY_USERNAME }}
